CREATE OR REPLACE TABLE ECOMMERCE.PUBLIC.ORDERS (
    ORDER_ID STRING,
    ORDER_DATE DATE,
    CUSTOMER_ID STRING,
    PRODUCT_CATEGORY STRING,
    ORDER_AMOUNT FLOAT,
    PAYMENT_METHOD STRING
);
 

