-- Total sales by product category
SELECT 
  PRODUCT_CATEGORY,
  COUNT(*) AS TOTAL_ORDERS,
  ROUND(SUM(ORDER_AMOUNT), 2) AS TOTAL_SALES
FROM 
  ECOMMERCE.PUBLIC.ORDERS
GROUP BY 
  PRODUCT_CATEGORY
ORDER BY 
  TOTAL_SALES DESC;

-- Daily revenue
SELECT 
  ORDER_DATE,
  ROUND(SUM(ORDER_AMOUNT), 2) AS DAILY_REVENUE
FROM 
  ECOMMERCE.PUBLIC.ORDERS
GROUP BY 
  ORDER_DATE
ORDER BY 
  ORDER_DATE;
 

